### PR TITLE
Fix/#6768 allowance transaction data download

### LINKED ISSUE #6768: CAMPD allowance transaction data download bug
New production bug in allowance transaction data- Can't download preview-able data when retired program filters are selected. Preview is available and working see Request tracker ticket: #77830 for user that reported this bug.
	• Preview uses reg API and download uses streaming API

Low priority (1.8) try for sprint 24

### PR DESCRIPTION
**Pull request by ergjustin**
## Ticket
[CAMPD allowance transaction data download bug](https://github.com/US-EPA-CAMD/easey-ui/issues/6768)

## Changes
extract isActiveOnly from the object

### CODE REVIEW

File: src/validators/is-allowance-program.validator.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ export class IsAllowanceProgramValidator
       found = await this.entityManager.findOneBy(ProgramCode, {
         programCode: value.toUpperCase(),
         allowanceUIFilter: 1,
-        tradingEndDate: IsNull(),
+        tradingEndDate: null,
```
Comment (maxdiebold-erg) [inline src/validators/is-allowance-program.validator.ts]: The version of TypeORM we're using treats `null` the same as `undefined` in queries, i.e. it strips the condition from the WHERE clause.  In this case, we _do_ want to ensure that `tradingEndDate` is null when the `isActiveOnly` flag is set, so `IsNull()` is correct.

However, that flag is set to `false` in all invocations of the `IsAllowanceProgram` pipe, so this block shouldn't ever be entered. It is being entered because of a bug in extracting the constraints above: each array item is an object, so object destructuring should be used to extract the relevant property in line 18 above:
```typescript
const { isActiveOnly } = args.constraints[0];
```

**Review by maxdiebold-erg — CHANGES_REQUESTED** [review]
Good find! I agree that the bug is in `is-allowance-program.validator.ts`, but I think the actual culprit is on a different line than where you found. I've left a suggestion below.

In addition, I think this will require that the validator is updated in the `develop` branch to use the proper destructuring _and_ to use `IsNull()` rather than `null`.

**Review by maxdiebold-erg — APPROVED** [review]
Looks good!
